server:
  port: 8001

#management:
#  security:
#    enabled: false

spring:
  application:
    name: spring-boot-mybatis-template

  datasource:
#    data: classpath:db/data.sql
#    schema: classpath:db/schema.sql
#    hikari:
#      jdbc-url: jdbc:h2:mem:h2test
#      driver-class-name: org.h2.Driver
#      username: zbook
#      password: zbook
#    type: com.zaxxer.hikari.HikariDataSource
    url: jdbc:h2:mem:h2test
    driver-class-name: org.h2.Driver
    username: root
    password: 123456

mybatis:
  config-location: classpath:mybatis/**/*.xml
  type-aliases-package: com.tbp.spring.boot.jps.template.entity
  configuration:
    # 配置驼峰命名转换 在进行sql查询和初始化实体时mybatis会为我们自动转化
    map-underscore-to-camel-case: true
mapper:
  mappers: com.tbp.spring.boot.mybatis.template.mapper.BaseMapper
  identity: MYSQL
pagehelper:
  helper-dialect: mysql
  reasonable: true
  support-methods-arguments: true
  params: count=countSql